### ISSUE TITLE
Will the code released?

### ISSUE THREAD

**Issue by Anonymous-so** [niluthpol/RGB2LIDAR#1]
Hi @niluthpol ,thanks for the excellent work.
Will the RGB2LIDAR code be released for more details about the model?

Looking forward to your reply.

**Comment by niluthpol** [comment]
Hi, Thanks for your interest! Unfortunately, we do not intend to release the RGB2LIDAR code.

**Comment by CVTangYong** [comment]
Hi, @niluthpol 
Can you tell me how to view the radar depth image in the dataset? Does it need to be processed before it can be viewed?
Looking forward to your reply.
