### ISSUE TITLE
how to view the radar depth image in the dataset?

### ISSUE THREAD

**Issue by Sugar1y** [niluthpol/RGB2LIDAR#2]
Hi,@niluthpol 
Can you tell me how to view the radar depth image in the dataset? Does it need to be processed before it can be viewed?
Looking forward to your reply.

**Comment by niluthpol** [comment]
You can use a 16 bin image viewer like IrfanView

To visualize with a rgb colormap, you can take a look at the following link:
https://stackoverflow.com/questions/13840013/opencv-how-to-visualize-a-depth-image
